n1 = int(input('Um valor: '))
n2 = int(input('Outro valor: '))
print(f'A soma vale {n1+n2}')
s = (n1 + n2)
m = (n1 * n2)
d = (n1 / n2)
di = (n1 // n2)
e = (n1 ** n2)
print(f'A some é {s}, o produto é {m} e a divisão é {d}', end=' ')
print(f'Divisão inteira é {di} e potencia é {e}')